"""Add TaskStatusEnum, and add task status field

Revision ID: 1443d02c8c2e
Revises: db7aa8ff0b9a
Create Date: 2025-11-23 02:33:47.250627

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1443d02c8c2e'
down_revision: Union[str, Sequence[str], None] = 'db7aa8ff0b9a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

task_status_enum = sa.Enum(
    'BACKLOG', 'TO_DO', 'IN_PROGRESS', 'TESTING', 'DONE',
    name='task_status'
)

def upgrade() -> None:
    """Upgrade schema."""
    task_status_enum.create(op.get_bind())
    op.add_column('tasks', sa.Column('status', task_status_enum, nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'status')
    task_status_enum.drop(op.get_bind())

    # ### end Alembic commands ###
